"""Build the collection compendium from the installed game's own data.

The catalog is intentionally independent from map markers.  It enumerates every
named inventory item from the game's localized FMG tables, classifies it using
the same category rules as the map, and attaches acquisition evidence that can
be derived reliably from game resources:

  * map treasure / scripted pickup markers generated by extract_items.py
  * one-time enemy/script rewards generated by extract_unique_drops.py
  * presence in ItemLotParam_enemy (farmable/random enemy drop)
  * presence in ItemLotParam_map (map/script reward with no resolvable marker)

It does NOT scrape a wiki or invent route prose.  If the game files do not tell
us which human-readable NPC/location is responsible, the UI says so plainly.

    python tools/extract_catalog.py -> data/catalog.json
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections import defaultdict

reconfigure = getattr(sys.stdout, "reconfigure", None)
if reconfigure:
    reconfigure(encoding="utf-8")
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from erlib import fmg, oodle, param, paramdef
import erlib.mfg_categories as mfg_categories
import erlib.modfiles as modfiles
from erlib.dvdbnd import DvdBnd
from erlib.gamepath import require_game_dir
from build_markers import LOCALES

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFS = os.path.join(ROOT, "data", "paramdefs")

TYPE_TABLES = {
    "goods": (1, "GoodsName"),
    "weapon": (2, "WeaponName"),
    "protector": (3, "ProtectorName"),
    "accessory": (4, "AccessoryName"),
    "gem": (5, "GemName"),
}

PARAM_TABLES = {
    "goods": "EquipParamGoods",
    "weapon": "EquipParamWeapon",
    "protector": "EquipParamProtector",
    "accessory": "EquipParamAccessory",
    "gem": "EquipParamGem",
}

# Categories that behave like a full-collection checklist.  Everything else is
# still emitted and can be shown via "all items", but bulk consumables/materials
# do not dilute the default completion percentage.
COLLECTION_CATEGORIES = {
    # Permanent/non-consumed collection identities.  Consumable progression
    # items (Larval Tears, Stonesword Keys, Deathroot, Bell Bearings after
    # turning them in, etc.) remain browsable under “all items”, but are not
    # counted in the default completion percentage because current inventory
    # cannot prove they were never acquired and subsequently spent/handed in.
    "armaments", "armour", "talismans", "ashes_of_war", "spirits",
    "crystal_tears", "incantations", "sorceries", "reusables",
    "prattling_pates", "cookbooks", "whetblades", "memory_stones",
    "pots_n_perfumes", "great_runes", "world_maps", "steed_appearances",
    # ERR/Reforged-specific permanent collections, when those rows exist.
    "fortunes", "sealed_curios",
}

DESC_SUFFIXES = ("Info", "Caption")

# Detail fields mirror the values shown in the in-game equipment status panel.
# Keep the catalog data numeric and locale-neutral; the UI supplies translated
# labels so a refreshed catalog can still be used with every supported locale.
DETAIL_FIELDS = {
    "weapon": {
        "weight": "weight", "durability": "durabilityMax",
        "attack": ("attackBasePhysics", "attackBaseMagic", "attackBaseFire", "attackBaseThunder", "attackBaseDark"),
        "guard": ("physGuardCutRate", "magGuardCutRate", "fireGuardCutRate", "thunGuardCutRate", "darkGuardCutRate"),
        "requirements": ("properStrength", "properAgility", "properMagic", "properFaith", "properLuck"),
        "scaling": ("correctStrength", "correctAgility", "correctMagic", "correctFaith", "correctLuck"),
        "status_guard": ("poisonGuardResist", "diseaseGuardResist", "bloodGuardResist", "freezeGuardResist", "sleepGuardResist", "madnessGuardResist"),
    },
    "protector": {
        "weight": "weight", "durability": "durabilityMax",
        "negation": ("neutralDamageCutRate", "magicDamageCutRate", "fireDamageCutRate", "thunderDamageCutRate", "darkDamageCutRate"),
        "resistance": ("resistPoison", "resistDisease", "resistBlood", "resistFreeze", "resistSleep", "resistMadness"),
        "poise": "toughnessCorrectRate",
    },
}


def _number(value):
    """Return compact JSON-safe numeric values without floating-point noise."""
    if isinstance(value, float):
        return round(value, 2)
    return value


def _values(fields, names):
    return [_number(fields.get(name, 0)) for name in names]


def item_details(typ, category, fields):
    """Extract useful, stable detail data from an inventory Param row."""
    details = {}
    spec = DETAIL_FIELDS.get(typ)
    if spec:
        for key, field_names in spec.items():
            if isinstance(field_names, tuple):
                details[key] = _values(fields, field_names)
            else:
                details[key] = _number(fields.get(field_names, 0))
        if typ == "protector":
            # Protector rows store received-damage multipliers. Convert them
            # into the negation percentages the game shows to the player.
            details["negation"] = [round((1 - value) * 100, 1) for value in details["negation"]]

    # These ids are intentionally exposed alongside the game's item text. They
    # let players identify effects precisely even where the executable has no
    # separate, human-readable parameter description.
    effect_names = {
        "accessory": ("residentSpEffectId1", "residentSpEffectId2", "residentSpEffectId3", "residentSpEffectId4"),
        "gem": ("spEffectId0", "spEffectId1", "spEffectId2"),
        "goods": ("spEffectId", "spEffectId2", "spEffectId3"),
    }
    ids = [int(fields.get(name, -1)) for name in effect_names.get(typ, ()) if int(fields.get(name, -1)) > 0]
    if ids:
        details["effectIds"] = sorted(set(ids))
    if typ == "goods":
        details.update({
            "weight": _number(fields.get("weight", 0)),
            "maxNum": int(fields.get("maxNum", 0)),
            "maxRepositoryNum": int(fields.get("maxRepositoryNum", 0)),
            "consumeMP": int(fields.get("consumeMP", 0)),
            "consumeHP": int(fields.get("consumeHP", -1)),
            "consumable": bool(fields.get("isConsume", 0)),
            "useLimitCategory": int(fields.get("useLimitCategory", 0)),
        })
    if typ in {"accessory", "gem"}:
        details["weight"] = _number(fields.get("weight", 0))
    for price_name in ("basicPrice", "saleValue", "sellValue"):
        value = fields.get(price_name)
        if isinstance(value, int) and value > 0:
            details["price"] = value
            break
    return {key: value for key, value in details.items() if value not in (0, -1, [], False)}


def clean_text(text: str) -> str:
    if not text or text.startswith("%null%") or "[error]" in text.lower():
        return ""
    return text.replace("\r\n", "\n").strip()


def load_messages(dvd, mod, helper):
    out = {}
    for loc, folder in LOCALES.items():
        tables = {}
        for fn in ("item.msgbnd.dcx", *(f"item_dlc{i:02d}.msgbnd.dcx" for i in range(1, 10)), "item_tarnished.msgbnd.dcx"):
            path = f"/msg/{folder}/{fn}"
            if not modfiles.has(dvd, mod, path):
                continue
            data = modfiles.read(dvd, mod, path)
            for key, values in fmg.load_msgbnd(data, oodle=helper).items():
                tables.setdefault(key.split("_dlc")[0], {}).update(values)
        out[loc] = tables
    return out


def load_menu_messages(dvd, mod, helper):
    out = {}
    for loc, folder in LOCALES.items():
        tables = {}
        for fn in ("menu.msgbnd.dcx", *(f"menu_dlc{i:02d}.msgbnd.dcx" for i in range(1, 10)), "menu_tarnished.msgbnd.dcx"):
            path = f"/msg/{folder}/{fn}"
            if not modfiles.has(dvd, mod, path):
                continue
            data = modfiles.read(dvd, mod, path)
            for key, values in fmg.load_msgbnd(data, oodle=helper).items():
                tables.setdefault(key.split("_dlc")[0], {}).update(values)
        out[loc] = tables
    return out


def find_gesture_table(messages):
    """Locate the gesture-name FMG and its save-slot id offset.

    GestureGameData stores canonical *odd* ids (Bow=1, Warm Welcome=13,
    Finger Snap=147).  Some message dumps/tools expose the same table with
    zero-based/even keys (0, 12, 146), so detect both representations instead
    of baking one convention into the catalog.  The returned offset converts
    an FMG row id to the canonical save id.
    """
    profiles = (
        ({1: "bow", 13: "warm welcome", 147: "finger snap"}, 0),
        ({0: "bow", 12: "warm welcome", 146: "finger snap"}, 1),
    )
    best = None
    for table, values in messages.get("en", {}).items():
        for anchors, save_offset in profiles:
            score = sum(clean_text(values.get(i, "")).lower() == name
                        for i, name in anchors.items())
            if "gesture" in table.lower():
                score += 1
            # Real gesture tables are small; this rejects broad menu-text tables
            # that merely happen to reuse one of these numeric ids.
            if not (10 <= len(values) <= 512):
                score -= 2
            candidate = (score, table, save_offset)
            if best is None or candidate[0] > best[0]:
                best = candidate
    return (best[1], best[2]) if best and best[0] >= 2 else (None, 0)


def localized(messages, table, iid):
    en = clean_text(messages.get("en", {}).get(table, {}).get(iid, ""))
    if not en:
        return None
    return {loc: clean_text(messages.get(loc, {}).get(table, {}).get(iid, "")) or en
            for loc in LOCALES}


def description(messages, name_table, iid):
    stem = name_table[:-4] if name_table.endswith("Name") else name_table
    result = {}
    for loc in LOCALES:
        parts = []
        tables = messages.get(loc, {})
        en_tables = messages.get("en", {})
        for suffix in DESC_SUFFIXES:
            tbl = stem + suffix
            text = clean_text(tables.get(tbl, {}).get(iid, ""))
            if not text:
                text = clean_text(en_tables.get(tbl, {}).get(iid, ""))
            if text and text not in parts:
                parts.append(text)
        if parts:
            result[loc] = "\n\n".join(parts)
    return result


def load_marker_sources(params=None, lot_def=None):
    """Read existing map/drop marker files and attach every ItemLot slot.

    New marker files carry `lotItems` directly.  Older generated maps do not,
    so when Params are available we reconstruct the same list from the marker's
    ItemLot id.  This keeps the one-step catalog rebuild useful on an existing
    installation instead of forcing a full map re-extraction first.
    """
    out = defaultdict(list)
    # Boss markers are the one reliable source of a human-readable enemy name:
    # their defeat flag is set by the same encounter that awards the item.
    boss_names = {}
    marker_path = os.path.join(ROOT, "data", "markers.json")
    try:
        for marker in json.load(open(marker_path, encoding="utf-8")).get("markers", []):
            if marker.get("cat") == "boss" and marker.get("flag"):
                names = marker.get("names") or {}
                name = clean_text(names.get("zh") or names.get("en") or "")
                if name:
                    boss_names[int(marker["flag"])] = name
    except (OSError, ValueError):
        pass
    specs = [
        ("items.json", "pickup"),
        ("unique_drops.json", "unique_drop"),
    ]
    for fn, kind in specs:
        path = os.path.join(ROOT, "data", fn)
        if not os.path.exists(path):
            continue
        try:
            doc = json.load(open(path, encoding="utf-8"))
        except (OSError, ValueError):
            continue
        for marker in doc.get("markers", []):
            entries = marker.get("lotItems") or []
            if not entries and marker.get("itemId") and marker.get("itemCategory"):
                entries = [{
                    "itemId": marker.get("itemId"),
                    "itemCategory": marker.get("itemCategory"),
                }]
            if not entries and params is not None and lot_def is not None and marker.get("lot"):
                lot = int(marker["lot"])
                tables = []
                if kind == "pickup":
                    tables = [params.get("ItemLotParam_map")]
                else:
                    # Scripted/unique rewards can originate from either table.
                    tables = [params.get("ItemLotParam_enemy"), params.get("ItemLotParam_map")]
                rows = []
                for table in tables:
                    if table:
                        row = next((r for r in table.rows if r.id == lot), None)
                        if row is not None:
                            rows.append(row)
                seen_entries = set()
                for row in rows:
                    for slot in range(1, 9):
                        iid = lot_def.get(row.data, f"lotItemId{slot:02d}") or 0
                        cat = lot_def.get(row.data, f"lotItemCategory{slot:02d}") or 0
                        sig = (int(cat), int(iid))
                        if iid and cat and sig not in seen_entries:
                            seen_entries.add(sig)
                            entries.append({"itemId": int(iid), "itemCategory": int(cat)})
            source = {
                "kind": kind,
                "marker": marker.get("id"),
                "map": marker.get("map"),
                "lot": marker.get("lot"),
                "flag": marker.get("flag"),
            }
            if marker.get("npc"):
                source["npc"] = marker["npc"]
            if marker.get("model"):
                source["model"] = marker["model"]
            enemy_name = boss_names.get(int(marker.get("flag") or 0))
            if enemy_name:
                source["enemyName"] = enemy_name
            for entry in entries:
                iid = entry.get("itemId")
                cat = entry.get("itemCategory")
                if not iid or not cat:
                    continue
                out[(int(cat), int(iid))].append(dict(source))
    return out


def add_lot_sources(params, lot_def, out):
    """Attach coarse-but-reliable game-file acquisition evidence.

    We deliberately do not claim an enemy name without a trustworthy name/link
    chain.  The UI can still tell the user that an otherwise-unlocated armour
    piece is a random enemy drop rather than a missing map pickup.
    """
    for param_name, kind in (("ItemLotParam_enemy", "enemy_drop"),
                             ("ItemLotParam_map", "map_reward")):
        table = params.get(param_name)
        if not table:
            continue
        for row in table.rows:
            for slot in range(1, 9):
                iid = lot_def.get(row.data, f"lotItemId{slot:02d}") or 0
                cat = lot_def.get(row.data, f"lotItemCategory{slot:02d}") or 0
                bp = lot_def.get(row.data, f"lotItemBasePoint{slot:02d}") or 0
                if not iid or not cat or bp <= 0:
                    continue
                key = (int(cat), int(iid))
                # One row is enough to establish the acquisition class.  Keep a
                # few ids for diagnostics instead of bloating catalog.json with
                # thousands of repeated farmable-drop rows.
                rows = [x for x in out[key] if x.get("kind") == kind]
                if len(rows) < 4:
                    out[key].append({"kind": kind, "lot": row.id, "flag": lot_def.as_dict(row.data, ["getItemFlagId"]).get("getItemFlagId")})


def _spirit_name_root(name: str) -> str:
    """English display-name identity with the reinforcement suffix removed."""
    return re.sub(r"\s+\+\d+\s*$", "", clean_text(name)).strip().casefold()


def build_canonical_maps(messages, params):
    """Return concrete Param id -> collection identity maps.

    Weapons and Spirit Ashes are the two collection families whose concrete
    save ids can change without the player obtaining a new collectible:

      * weapon save id = affinity-row id + reinforcement level; affinity rows
        are spaced by 100 and the uninfused identity is the surrounding 10000
        group.  We only collapse to that group when an actual base row exists.
      * Spirit Ashes are real EquipParamGoods rows for each reinforcement tier.
        Vanilla and ERR do not use exactly the same suffix spacing, so deriving
        the identity from ``id % 10`` alone is unsafe.  Elden Ring encodes
        Spirit Ash reinforcement in the low two decimal digits (+0..+10), so
        group installed Param rows by their 100-id reinforcement block and
        English name with a trailing ``+N`` removed.  Then select the explicit
        unreinforced row (or the smallest row as a defensive fallback).

    These maps are also emitted as catalog aliases.  The runtime save resolver
    can therefore map a concrete Spirit Ash id exactly, without applying broad
    arithmetic to ordinary Goods ids.
    """
    en_tables = messages.get("en", {})
    weapon_names = en_tables.get("WeaponName", {})
    goods_names = en_tables.get("GoodsName", {})

    weapon_param = params.get("EquipParamWeapon") if params else None
    goods_param = params.get("EquipParamGoods") if params else None
    weapon_valid = {int(r.id) for r in weapon_param.rows} if weapon_param else set(map(int, weapon_names))
    goods_valid = {int(r.id) for r in goods_param.rows} if goods_param else set(map(int, goods_names))

    weapon_map = {}
    for raw_iid, raw_name in weapon_names.items():
        iid = int(raw_iid)
        if iid not in weapon_valid:
            continue
        name = clean_text(raw_name)
        if not name:
            continue
        cat = mfg_categories.categorise(iid, name, 2)
        if cat == "ammo":
            weapon_map[iid] = iid
            continue
        base = iid - (iid % 10000)
        base_name = clean_text(weapon_names.get(base, ""))
        # Mods may use a different id scheme.  Never merge a row into a
        # non-existent base merely because vanilla arithmetic suggests one.
        if base in weapon_valid and base_name and mfg_categories.categorise(base, base_name, 2) != "ammo":
            weapon_map[iid] = base
        else:
            weapon_map[iid] = iid

    spirit_groups = defaultdict(list)
    for raw_iid, raw_name in goods_names.items():
        iid = int(raw_iid)
        if iid not in goods_valid:
            continue
        name = clean_text(raw_name)
        if not name or mfg_categories.categorise(iid, name, 1) != "spirits":
            continue
        root = _spirit_name_root(name)
        if not root:
            continue
        spirit_groups[(iid // 100, root)].append((iid, name))

    spirit_map = {}
    for group in spirit_groups.values():
        plain = [iid for iid, name in group if _spirit_name_root(name) == name.casefold().strip()]
        canonical = min(plain or [iid for iid, _ in group])
        for iid, _ in group:
            spirit_map[iid] = canonical

    return weapon_map, spirit_map


def canonical_item_id(typ: str, iid: int, marker_cat: str, weapon_map=None, spirit_map=None) -> int:
    if typ == "weapon":
        if marker_cat == "ammo":
            return iid
        if weapon_map and iid in weapon_map:
            return weapon_map[iid]
        # ItemLots can encode a reinforced weapon id that has no FMG/Param row.
        # Strip only a plausible ER reinforcement suffix (+0..+25), then the
        # affinity.  Do not blindly round arbitrary ids.
        level = iid % 100
        affinity_row = iid - level if level <= 25 else iid
        if weapon_map and affinity_row in weapon_map:
            return weapon_map[affinity_row]
        # Unknown/modded id shape: preserve the exact affinity row rather than
        # inventing a collection identity that does not exist in the scanned
        # Param/FM G data.  It simply will not attach to a catalog row.
        return affinity_row
    if typ == "goods" and marker_cat == "spirits":
        if spirit_map and iid in spirit_map:
            return spirit_map[iid]
        # Defensive fallback for a modded/unlisted spirit reward.  Reinforcement
        # occupies the low two decimal digits (+0..+10 in Elden Ring).  Keep
        # this fallback generator-only: the runtime resolver consumes exact
        # aliases emitted from the installed game's Param rows.
        rem = iid % 100
        if rem <= 10:
            return iid - rem
    return iid


def enrich_catalog(items, params, dvd, mod, helper):
    """Use Param and message provenance, not numeric DLC thresholds."""
    provenance = {}; base_ids = {}; candidates = []
    # Optional explicit, version-specific mappings. Unknown numeric resource
    # packs stay unknown; no invented entitlement/ID-range guesses.
    overrides_path = os.path.join(ROOT, "data", "content-pack-overrides.json")
    overrides = {}
    if os.path.isfile(overrides_path):
        with open(overrides_path, encoding="utf-8") as stream:
            overrides = json.load(stream)
    for fn in ("item.msgbnd.dcx", *(f"item_dlc{i:02d}.msgbnd.dcx" for i in range(1, 10)), "item_tarnished.msgbnd.dcx"):
        path = f"/msg/engus/{fn}"
        if not modfiles.has(dvd, mod, path):
            continue
        for raw_table, values in fmg.load_msgbnd(modfiles.read(dvd, mod, path), oodle=helper).items():
            table = raw_table.split("_dlc")[0]
            # The outer DLC bundle also carries base tables. Only the inner
            # table suffix is provenance; the bundle filename is not.
            origin = raw_table
            match = re.search(r"_dlc(\d+)", origin, re.I)
            explicit = overrides.get("sources", {}).get(origin)
            pack = explicit or ("褪色者礼包" if "tarnished" in origin.lower() else
                               "黄金树幽影" if match and int(match[1]) == 1 else
                               f"扩展内容 DLC{int(match[1]):02d}（归属待确认）" if match else "")
            for iid, name in values.items():
                if not clean_text(name):
                    continue
                if not pack:
                    base_ids.setdefault(table, set()).add(iid)
                else:
                    candidates.append((table, iid, pack))
    for table, iid, pack in candidates:
        if iid not in base_ids.get(table, set()):
            provenance[(table, iid)] = pack
    # A selected mod's new IDs are identified against unmodified game text.
    vanilla = load_messages(dvd, None, helper).get("en", {}) if mod else {}
    rows = {}; defs = {}
    for typ, pname in PARAM_TABLES.items():
        table = params.get(pname)
        if table:
            rows[typ] = {int(r.id): r for r in table.rows}
            defs[typ] = paramdef.load(os.path.join(DEFS, pname + ".xml"))
    for item in items:
        typ = item["type"]; iid = int(item["id"])
        table = TYPE_TABLES.get(typ, (None, ""))[1]
        pack = provenance.get((table, iid), "")
        if mod and table and iid not in vanilla.get(table, {}):
            # Keep the actual selected mod label; do not mislabel all mods as a DLC.
            label = os.path.basename(os.path.normpath(str(mod)))
            pack = "模组新增：" + label
        pack = overrides.get("items", {}).get(item.get("key"), pack)
        if pack:
            item["contentPack"] = pack
        row = rows.get(typ, {}).get(iid); definition = defs.get(typ)
        if row is None or definition is None:
            continue
        fields = definition.as_dict(row.data)
        icon_id = fields.get("iconId", fields.get("iconIdM"))
        if isinstance(icon_id, int) and icon_id > 0:
            item["itemIconId"] = icon_id
            item["itemIcon"] = f"items/{icon_id}.png"
        if item.get("category") == "world_maps":
            flags = [src.get("flag") for src in item.get("sources", [])
                     if isinstance(src.get("flag"), int) and src["flag"] > 0]
            if flags:
                item["acquisitionFlags"] = sorted(set(flags))
        details = item_details(typ, item.get("category", ""), fields)
        if details:
            item["details"] = details


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--game-dir", default=None)
    ap.add_argument("--mod-dir", default=None)
    args = ap.parse_args()

    game = require_game_dir(args.game_dir)
    mod = modfiles.find_mod_dir(args.mod_dir)
    dvd = DvdBnd(game, cache_dir=os.path.join(ROOT, "cache"), verbose=False)
    helper = oodle.make_helper(game)

    print("loading localized item text ...")
    messages = load_messages(dvd, mod, helper)
    if not messages.get("en"):
        raise SystemExit("could not read English item message tables")
    menu_messages = load_menu_messages(dvd, mod, helper)
    gesture_table, gesture_id_offset = find_gesture_table(menu_messages)
    if gesture_table:
        print(f"  gesture names: {gesture_table} ({len(menu_messages['en'].get(gesture_table, {}))} rows; "
              f"save-id offset {gesture_id_offset:+d})")
    else:
        print("  warning: gesture name table not identified; gesture catalog rows will be omitted")

    sources = defaultdict(list)
    params = {}
    try:
        params = param.load_params(modfiles.regulation_path(game, mod))
        lot_def = paramdef.load(os.path.join(DEFS, "ItemLotParam.xml"))
        sources = load_marker_sources(params, lot_def)
        add_lot_sources(params, lot_def, sources)
    except Exception as exc:
        print(f"warning: ItemLot source scan skipped: {exc}")

    weapon_canonical, spirit_canonical = build_canonical_maps(messages, params)

    items_by_key = {}
    en_tables = messages["en"]
    for typ, (lot_cat, table) in TYPE_TABLES.items():
        names = en_tables.get(table, {})
        param_table = params.get(PARAM_TABLES[typ]) if params else None
        valid_ids = {int(r.id) for r in param_table.rows} if param_table else None
        for iid in sorted(names):
            if valid_ids is not None and int(iid) not in valid_ids:
                continue
            names_loc = localized(messages, table, iid)
            if not names_loc:
                continue
            en_name = names_loc["en"]
            low_name = en_name.lower()
            if "dlc dummy" in low_name:
                continue
            # These are equipment-slot sentinels, not things the player can
            # collect. Filtering them avoids a permanent false 'missing' row.
            if typ in {"weapon", "protector"} and low_name in {"unarmed", "head", "body", "arms", "legs"}:
                continue
            marker_cat = mfg_categories.categorise(iid, en_name, lot_cat)
            if typ == "goods" and low_name.startswith("map:"):
                marker_cat = "world_maps"
            elif typ == "goods" and "great rune" in low_name and "rune arc" not in low_name:
                marker_cat = "great_runes"
            canonical = canonical_item_id(typ, int(iid), marker_cat, weapon_canonical, spirit_canonical)
            key = (typ, canonical)

            # Collapse weapon affinity/upgrade rows and Spirit Ash reinforcement
            # levels into one collection identity. Prefer the real base row's
            # wording/description whenever it is present.
            existing = items_by_key.get(key)
            aliases = set(existing.get("aliases", [])) if existing else set()
            aliases.add(int(iid))
            prefer = existing is None or int(iid) == canonical
            if prefer:
                row = {
                    "key": f"{typ}:{canonical}",
                    "type": typ,
                    "id": canonical,
                    "category": marker_cat,
                    "names": names_loc,
                    "icon": mfg_categories.icon_for(marker_cat),
                    "collectible": marker_cat in COLLECTION_CATEGORIES,
                }
                desc = description(messages, table, iid)
                if desc:
                    row["descriptions"] = desc
                row["aliases"] = sorted(aliases)
                items_by_key[key] = row
            else:
                existing["aliases"] = sorted(aliases)

    # Gestures are not GaItems.  Their acquired IDs live in the separate
    # GestureGameData save block, so add them as a sixth catalog type using the
    # installed game's own localized menu FMG.
    if gesture_table:
        for iid in sorted(menu_messages.get("en", {}).get(gesture_table, {})):
            menu_id = int(iid)
            save_id = menu_id + gesture_id_offset
            # GestureGameData canonical ids are positive and odd.  Filtering
            # here also prevents unrelated rows from a falsely broad FMG table
            # becoming collection entries.
            if save_id <= 0 or (save_id & 1) == 0 or save_id == 0xfe:
                continue
            names_loc = localized(menu_messages, gesture_table, menu_id)
            if not names_loc:
                continue
            items_by_key[("gesture", save_id)] = {
                "key": f"gesture:{save_id}",
                "type": "gesture",
                "id": save_id,
                "category": "gestures",
                "names": names_loc,
                "icon": mfg_categories.icon_for("gestures"),
                "collectible": True,
            }

    # Attach sources.  Weapon lot ids normally point at the base row, but use
    # the same canonicalizer so an unusual affinity-bearing reward still joins.
    for (cat, iid), srcs in sources.items():
        typ = {1: "goods", 2: "weapon", 3: "protector", 4: "accessory", 5: "gem"}.get(cat)
        if not typ:
            continue
        # Determine the item class from its English name when possible before
        # canonicalising a weapon reward.
        marker_cat = None
        table = TYPE_TABLES[typ][1]
        name = clean_text(en_tables.get(table, {}).get(iid, ""))
        if name:
            marker_cat = mfg_categories.categorise(iid, name, cat)
            low_name = name.lower()
            if typ == "goods" and low_name.startswith("map:"):
                marker_cat = "world_maps"
            elif typ == "goods" and "great rune" in low_name and "rune arc" not in low_name:
                marker_cat = "great_runes"
        cid = canonical_item_id(typ, int(iid), marker_cat or ("armaments" if typ == "weapon" else "misc"), weapon_canonical, spirit_canonical)
        row = items_by_key.get((typ, cid))
        if not row:
            continue
        seen = {(x.get("kind"), x.get("marker"), x.get("lot")) for x in row.get("sources", [])}
        for src in srcs:
            sig = (src.get("kind"), src.get("marker"), src.get("lot"))
            if sig not in seen:
                row.setdefault("sources", []).append(src)
                seen.add(sig)

    # Alias integrity is safety-critical: one concrete save id must never map to
    # two collection identities of the same GaItem type.
    alias_owner = {}
    for row in items_by_key.values():
        aliases = sorted(set(int(x) for x in row.get("aliases", [])) | {int(row["id"])})
        row["aliases"] = aliases
        for alias in aliases:
            sig = (row["type"], alias)
            other = alias_owner.get(sig)
            if other and other != row["key"]:
                raise SystemExit(f"catalog alias collision {sig}: {other} vs {row['key']}")
            alias_owner[sig] = row["key"]

    items = sorted(items_by_key.values(), key=lambda x: (x["category"], x["names"]["en"].lower(), x["id"]))
    enrich_catalog(items, params, dvd, mod, helper)

    cats = defaultdict(lambda: {"total": 0, "collectible": 0})
    for item in items:
        cats[item["category"]]["total"] += 1
        if item["collectible"]:
            cats[item["category"]]["collectible"] += 1

    out = {
        "schema": 2,
        "source": "game-files",
        "locales": list(LOCALES),
        "items": items,
        "categories": dict(cats),
        "notes": {
            "en": "Names/descriptions come from the installed game. Acquisition hints appear only where game resources provide reliable evidence. The default checklist excludes spendable/handed-in progression items; Show all items reflects current possession for those. No wiki text is bundled.",
            "zh": "名称与说明直接来自已安装游戏；获得方式仅在游戏资源能够可靠推导时显示。默认清单排除会消耗／上交的流程物品；“显示全部物品”中的这类物品仅反映当前持有量。不捆绑 Wiki 攻略文本。",
        },
    }
    path = os.path.join(ROOT, "data", "catalog.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False)
    collapsed_weapon = sum(1 for a, c in weapon_canonical.items() if a != c)
    collapsed_spirits = sum(1 for a, c in spirit_canonical.items() if a != c)
    print(f"catalog: {len(items):,} named items; default collectibles: {sum(1 for x in items if x['collectible']):,}")
    print(f"  normalized aliases: weapons={collapsed_weapon:,}, spirit tiers={collapsed_spirits:,}")
    print(f"-> {path} ({os.path.getsize(path):,} bytes)")
    dvd.close()


if __name__ == "__main__":
    main()
